checksumBehavior: update

yarnPath: .yarn/releases/yarn-4.3.0.cjs

packageExtensions:
  "jscpd@*":
    dependencies:
      "@jscpd/leveldb-store": "*"
  "@jscpd/html-reporter@*":
    dependencies:
      "@jscpd/finder": "*"
