name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: pnpm

            - uses: tiwariav/github-actions/cache-js-linters@main

            - run: corepack enable

            - run: pnpm install --frozen-lockfile

            - run: pnpm eslint --cache --cache-strategy=content --quiet "packages/*/src"

            - run: pnpm stylelint --cache "packages/*/src/**/*.css"

            - run: pnpm prettier --cache --check "packages/*/src"

            - run: pnpm jscpd packages

            - run: npx nx affected -t build

            - run: npx nx affected -t test
