name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - uses: tiwariav/github-actions/cache-js-linters@main

      - run: pnpm install --frozen-lockfile

      - run: pnpm eslint --no-cache --quiet packages/{js,react,ui,web}/src

      - run: pnpm stylelint --cache packages/*/src/**/*.css

      - run: pnpm prettier --cache --check packages/*/src

      - run: pnpm jscpd packages/*/src

      - run: pnpm nx affected -t build

      - run: pnpm nx affected -t test
